### ISSUE TITLE
Add some cool hover effect over Navigation items.

### ISSUE THREAD

**Issue by ankman007** [ankman007/Music-Website#1]
### Screenshot
![Screenshot (6)](https://github.com/ankman007/Music-Website/assets/108212023/565d49d7-0f3d-4d9c-bebf-4c0cf476e32b)

**Comment by vd89** [comment]
hay @ankman007  
will be fixing this in no time 
assign it to me

**Comment by ankman007** [comment]
> hay @ankman007 will be fixing this in no time assign it to me

Done

**Comment by vd89** [comment]
- have  fixed and raised the pr for the same 
-
