### ISSUE TITLE
[FEAT]: Add media queries for responsive design 

### ISSUE THREAD

**Issue by ankman007** [ankman007/Music-Website#11]
### Description 
Right now, there is no media queries for certain parts of the webpage. 

### To Do
You can add media queries for different screen sizes & make it responsive.

**Comment by sarafurd** [comment]
please assign this to me

**Comment by ankman007** [comment]
> please assign this to me

Done

**Comment by sarafurd** [comment]
Hi, sorry I was working on the issue. I had to rewrite some of the original code to make it responsive.
