### ISSUE TITLE
Fix logo on the navigation section of the home page 

### ISSUE THREAD

**Issue by ankman007** [ankman007/Music-Website#2]
### Description
Right not the main logo for website in Navigation bar is just a plain text. You will need to add a logo with file extension of any accepted file format (ai, eps, svg, png, jpg or pdf). 

###Screenshot
![assd](https://github.com/ankman007/Music-Website/assets/108212023/39c3bbf1-ea6d-41cd-9289-9e6b6684c0b1)

**Comment by SUBS2905** [comment]
I have updated the logo and did a PR.
Here is the logo for your reference.
![mytunes_logo](https://github.com/ankman007/Music-Website/assets/80648132/44a8e9f1-873c-46f0-a597-9caf94399bb0)

**Comment by Alekhya-Dharam** [comment]
please assign this to me.
can you pls add the hacktoberfest tag to this??

**Comment by Alekhya-Dharam** [comment]
> please assign this to me. can you pls add the hacktoberfest tag to this??

please reply ASAP
