### ISSUE TITLE
Update favicon on the home page 

### ISSUE THREAD

**Issue by ankman007** [ankman007/Music-Website#3]
### Description
You will need to find something related to music/songs/artists that relates to overall theme of this music website from site like favicon.io and add it as favicon.

### Screenshot
![tt](https://github.com/ankman007/Music-Website/assets/108212023/4e0b0d57-abc3-4e3e-b17a-89a73c7c6946)

**Comment by Alekhya-Dharam** [comment]
Please assign this to me

**Comment by ankman007** [comment]
> Please assign this to me

Done
