### ISSUE TITLE
Change the overall theme of the home page

### ISSUE THREAD

**Issue by ankman007** [ankman007/Music-Website#5]
### Description
Right now the colors & fonts in the home page seems off & don't match with each other. 

### To Do
You will need to find the colors that are compatible with each other from website like www.realtimecolors.com and re-design the home page with relation to those colors. Also, do change the fonts of the webpage and add some cool hover effect over the buttons.

**Comment by AhsanCommits** [comment]
I'm confident that I can contribute to this. Could you please assign it to me?

**Comment by AhsanCommits** [comment]
I have created a pull request and kindly review it.
Could you please reassign it to me?

@ankman007
